### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by rjb25** [s4w3d0ff/python-poloniex#122]
```
File "/usr/local/lib/python3.5/dist-packages/poloniex/__init__.py", line 279, in returnBalances
    return self.__call__('returnBalances')
  File "/usr/local/lib/python3.5/dist-packages/poloniex/retry.py", line 15, in wrapped
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/poloniex/__init__.py", line 175, in __call__
    return self.parseJson(ret.text)
  File "/usr/local/lib/python3.5/dist-packages/poloniex/__init__.py", line 197, in parseJson
    raise PoloniexError(jsonout['error'])
poloniex.PoloniexError: Connection timed out. Please try again.
```
Every other call I get an error like the above. I have tried making the timeout longer by doing `Poloniex(key, secret, timeout=80)` But this did not help. Any suggestions?

**Comment by s4w3d0ff** [comment]
I started to see these errors as well. 

It seems like poloniex may have a new server that relays messages between users and the 'actual' api(?). So you make a request and the first server determines if it is valid then sends it to the other server that processes the request. I'm guessing that the timeout error is coming from the 2nd server and the 1st is relaying the message. If this is true, setting the `timeout` param in this wrapper won't help, as the timeout is occurring between the 2 servers.

Only 'fix' I see is to try to capture these errors exclusively and retry the call again. I will try to work on the fix for the wrapper, but I am starting to run short of time at the moment.
