### ISSUE TITLE
Want to understand coach() a little deeper

### ISSUE THREAD

**Issue by techietrader** [s4w3d0ff/python-poloniex#130]
@s4w3d0ff 
Hi,
Firstly thanks for the api, its cool.
I have got this query to understand the Class- Coach()

Now that we all know the rate is 6 calls a second!
Please help me understand this-
Suppose , I call returnChartdata say every 300, 900 or any mentioned time interval for all the currencies in poloniex at once, how will it behave if Coach is True?
I m little new to programming and have encountered such situation first time alone with its solution but cant figure out how things will behave.
I went through Coach codes and I think the calls will delay every second once it hits 6 calls every second. Am i understanding it correctly?

Do I need to use some command in Coach class to delay calls? 
Suppose there are 100 coins listed on Polo and I call returnChartdata command for all coins in any period, which means 100 calls.
So how will things happen?

Can you explain?

**Comment by s4w3d0ff** [comment]
The period times in `returnChartData` have nothing to do with the coach.

The period times for `returnChartData` is the time period between candles, or the candle size.

If you get last months data for a market with 24h candles, the data returned from poloniex will be naturally smaller than last months data with 5 min candles. 

So if you try to get years worth of data in 5 min candles it is going to take noticeably longer to download. But the `Coach` only cares about sending the calls **out** and knows nothing about the response or how long it takes to download.

So changing the period size should not effect the coach at all, but it may slow down your overall program due to larger data downloads.

**Comment by techietrader** [comment]
> So if you try to get years worth of data in 5 min candles it is going to take noticeably longer to download. But the Coach only cares about sending the calls out and knows nothing about the response or how long it takes to download.

So when I am sending a call out which is restricted to 6 calls a second,
Will I breach the limit if I call data for all currencypair in one shot using public api be it for any period?

**Comment by s4w3d0ff** [comment]
Probably not, maybe if poloniex is taking a long time just to process the request but I think (hope) the retry function will catch the error (if one is returned) and try the failed call again. I might test this later, I am kinda curious...

**Comment by techietrader** [comment]
Thanks a lot mate for quick responses. Appreciated

**Comment by s4w3d0ff** [comment]
Seems like this is the error you will come across on those big downloads:
```
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
INFO:poloniex:-- delaying for 0s
```
which the retry function will catch and try again.

**Comment by techietrader** [comment]
Ah! okay.
Thanks a ton
