### ISSUE TITLE
poloniex.PoloniexError: Invalid json response returned

### ISSUE THREAD

**Issue by JorgeANino** [s4w3d0ff/python-poloniex#141]
from poloniex import Poloniex
polo = Poloniex()

print(polo("returnTicker")["BTC_ETH"])

What I'm doing wrong?

**Comment by JorgeANino** [comment]
No handlers could be found for logger "poloniex"
Traceback (most recent call last):
  File "C:/Users/jorge/LoopX/LoopX/GUI/FRONTEND/BACKEND/CryptoCurrency.py", line 4, in <module>
    print(polo("returnTicker")["BTC_ETH"])
  File "C:\Users\jorge\Anaconda2\lib\site-packages\poloniex\__init__.py", line 143, in retrying
    return func(*args, **kwargs)
  File "C:\Users\jorge\Anaconda2\lib\site-packages\poloniex\__init__.py", line 218, in __call__
    return self.handleReturned(ret.text)
  File "C:\Users\jorge\Anaconda2\lib\site-packages\poloniex\__init__.py", line 251, in handleReturned
    raise PoloniexError('Invalid json response returned')
poloniex.PoloniexError: Invalid json response returned

**Comment by s4w3d0ff** [comment]
try running your script with:
```
import logging
logging.basicConfig(level=logging.INFO)
```
This will show the logging error message that has the raw response from poloniex. In the past this has happened because of either Captcha or Cloudflare.

https://github.com/s4w3d0ff/python-poloniex/issues/111
https://github.com/s4w3d0ff/python-poloniex/issues/109

**Comment by mellertson** [comment]
I speculate it might be due to your physical location. Cloudfare is headquartered in San Francisco and lists four locations inside the US, one in London and one in Singapore. They might block people from accessing servers in their data centers from time to time in an attempt to tighten security.  It could be something else entirely, but it seems like one thing to check out. You might need to contact their security teams to put your IP address on a whitelist.

For me, located in Utah (at the moment), it's working just fine.

```
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import poloniex
>>> polo = poloniex.Poloniex()
>>> print(polo("returnTicker")["BTC_ETH"])
{u'last': u'0.08445438', u'quoteVolume': u'434955.48712973', u'high24hr': u'0.08640271', u'isFrozen': u'0', u'highestBid': u'0.08445438', u'percentChange': u'-0.01711481', u'low24hr': u'0.08067010', u'lowestAsk': u'0.08451701', u'id': 148, u'baseVolume': u'36498.12378390'}
```

**Comment by s4w3d0ff** [comment]
we now have proxies
`polo = poloniex.Poloniex(proxies={})`
