### ISSUE TITLE
Improvement: callLimit Coach declaration

### ISSUE THREAD

**Issue by yepla** [s4w3d0ff/python-poloniex#148]
Hello,
I want to know if it possible to use Coach with a different callLimit by the default timeFrame ?
In fact i use the poloniex module on different bot on the same host and i use Coach to not be ban.
But to be able to use different bot i must modify on each bot the module localy and change the callLimit to not be under 6 by second with all my bot.
It will be great when we define polo = poloniex.Poloniex(key, secret) put in it callLimit for the Coach.
Like that we could use the poloniex module install globaly on different bot runing on the same host without be ban !
Thanks.

**Comment by s4w3d0ff** [comment]
You can set the call limit of a coach and use that coach across other Poloniex instances like this:

```python
from poloniex import Poloniex, Coach

# create a coach with 1 second time frame, 6 call limit per timeframe
myCoach = Coach(timeFrame=1.0, callLimit=6)

# pass your custom coach as the 'coach' param to the polo object
polo = Poloniex(key, secret, coach=myCoach)
# this will also work:
polo.coach = myCoach

# if you want 'myCoach' to be used for other instances of the Poloniex class:
polo2 = Poloniex(coach=myCoach)

# now both 'polo' and 'polo2' will use 'myCoach' to restrict calls from both to an overall 6 calls per 1 second
```

Since `poloniex.Coach` uses a semaphore to restrict calls, the coach should be able to handle calls between threads.

I'm not sure if it is possible to share a coach across system processes, tho.

You can try using multiple api keys if you need to run multiple processes.

**Comment by yepla** [comment]
Thanks
