### ISSUE TITLE
How can I use "Push API" in your project?

### ISSUE THREAD

**Issue by archerhu77** [s4w3d0ff/python-poloniex#155]
Is there any way to active "Push API" for receive information(for example:ticker) from poloniex? Is it's not, could you please add this function to your project? I think it's better than use returnTicker frequently.

**Comment by s4w3d0ff** [comment]
Since I know very little about autobahn and asyncio, and the WAMP push api has proven to be buggy, I have been hesitant to incorporate the push api into this wrapper. Users have found that you can [access the undocumented push api](https://github.com/s4w3d0ff/python-poloniex/issues/115#issuecomment-311435848) that the poloniex website uses.

I added a basic working ticker example that uses the undocumented push api here: https://github.com/s4w3d0ff/python-poloniex/blob/v0.4.6/examples/ticker/wsMongoTicker.py (requires mongodb but can be easily hacked to save the ticker data to a dict or whatever)

I wouldn't mind adding a push api feature (in fact, I planned on adding one for some time) but don't want to spend hours writing it just to have poloniex change and break the code. I might soon create a branch that has the push api built-in, but will be kept out of the main release until poloniex can clean up their docs and/or api and I know that the code won't break overnight.

**Comment by Mantas779** [comment]
i use the Poloniex wrapper from s4w3d0ff

ticker = polo.returnTicker()['BTC_ARDR'] ['last']
highBid = polo.returnTicker()['BTC_ARDR'] ['highestBid']

**Comment by archerhu77** [comment]
@Mantas779 polo.returnTicker() only return ticker after request. But I want the tickers which push from poloniex server, so I want to use WAMP protocol. I found some code do the thing what I want use websocket, I just want to know is there any way to do that in @s4w3d0ff 's project. Thanks @s4w3d0ff .

**Comment by archerhu77** [comment]
@s4w3d0ff do you know is there anywhere can load currencyPair(id and name) from poloniex's api?

**Comment by s4w3d0ff** [comment]
the `id` from `returnTicker` might be what you are looking for, if not it could be `id` from `returnCurrencies`

```python
import poloniex
tick = poloniex.Poloniex().returnTicker()
for market in tick:
    print('%s = %s' % (market, str(tick[market]['id'])))
```
```
USDT_REP = 175
BTC_XVC = 98
BTC_PINK = 73
BTC_SYS = 92
BTC_EMC2 = 28
BTC_RADS = 158
BTC_SC = 150
BTC_MAID = 51
BTC_BCH = 189
BTC_GNT = 185
BTC_BCN = 7
BTC_REP = 174
BTC_BCY = 151
BTC_GNO = 187
XMR_NXT = 140
USDT_ZEC = 180
BTC_FCT = 155
USDT_ETH = 149
USDT_BTC = 121
BTC_LBC = 167
BTC_DCR = 162
USDT_ETC = 173
BTC_AMP = 160
BTC_XPM = 116
BTC_NXT = 69
BTC_VTC = 100
ETH_STEEM = 169
XMR_BLK = 130
BTC_PASC = 184
XMR_ZEC = 181
BTC_GRC = 40
BTC_NXC = 183
BTC_BTCD = 12
BTC_LTC = 50
BTC_DASH = 24
BTC_NAUT = 60
ETH_ZEC = 179
BTC_ZEC = 178
BTC_BURST = 15
BTC_BELA = 8
BTC_STEEM = 168
BTC_ETC = 171
BTC_ETH = 148
BTC_HUC = 43
BTC_STRAT = 182
BTC_LSK = 163
BTC_EXP = 153
BTC_CLAM = 20
ETH_REP = 176
XMR_DASH = 132
USDT_BCH = 191
USDT_DASH = 122
BTC_BLK = 10
BTC_XRP = 117
USDT_NXT = 124
BTC_NEOS = 63
BTC_BTS = 14
BTC_DOGE = 27
ETH_GNT = 186
BTC_SBD = 170
ETH_GNO = 188
BTC_XCP = 108
USDT_LTC = 123
BTC_BTM = 13
USDT_XMR = 126
ETH_LSK = 166
BTC_OMNI = 58
BTC_NAV = 61
BTC_FLDC = 31
ETH_BCH = 190
BTC_XBC = 104
BTC_DGB = 25
BTC_NOTE = 66
XMR_BTCD = 131
BTC_VRC = 99
BTC_RIC = 83
XMR_MAID = 138
BTC_STR = 89
BTC_POT = 74
BTC_XMR = 114
BTC_SJCX = 86
BTC_VIA = 97
BTC_XEM = 112
BTC_NMC = 64
ETH_ETC = 172
XMR_LTC = 137
BTC_ARDR = 177
BTC_FLO = 32
USDT_XRP = 127
BTC_GAME = 38
BTC_PPC = 75
XMR_BCN = 129
USDT_STR = 125
```

**Comment by archerhu77** [comment]
Thanks @s4w3d0ff , it's id in returnTicker but returnCurrencies.

**Comment by s4w3d0ff** [comment]
see #195
