### ISSUE TITLE
Pypi / releases / tests

### ISSUE THREAD

**Issue by goncalopp** [s4w3d0ff/python-poloniex#16]
Hi s4w3d0ff,

This repository is pretty popular :)

Have you considered doing releases on pypi? Or releases in github? Is the code stable enough for general use? (I'm asking because I need a package to communicate with poloniex, and I'd like to depend on this to avoid reinventing the wheel or copy-pasting code).

Also, are unit tests planned / patches accepted?

Thanks!

**Comment by s4w3d0ff** [comment]
Hey @goncalopp,

I would love to see this repo released on pypi. I hadn't done so yet because (as you mentioned) it does need unit tests.

IMO the code is stable enough for a git release but I would feel better if the doc-strings were formatted/cleaned-up/updated before making a release to pypi.

I accept/welcome all _sensible_ patches/improvements.

**Comment by s4w3d0ff** [comment]
Well, since all most legit pypi package names have been trolled by dead code :tada:, I am not exactly interested in registering this repo. Everyone can just keep using `pip install git+`... unless a troll finds a heart and links this repo, I really don't care... sorry.
![imgur](http://i.imgur.com/gXE57xd.gif)
