### ISSUE TITLE
Invalid JSON response

### ISSUE THREAD

**Issue by Pankul94** [s4w3d0ff/python-poloniex#176]
Hey
I am trying to get the 24h volume by using the method return24hVolume() method.

from poloniex import Poloniex
Poloniex().returnTicker()

This returns me with the HTML content of poloniex ending with an error "Invalid JSON response"
When I run https://poloniex.com/public?command=returnTicker in my browser I get the response in the JSON format.

Can you please let me know where am I going wrong
I have attached the response in the text file
[response.txt](https://github.com/s4w3d0ff/python-poloniex/files/1589549/response.txt)

Thanks
Pankul

**Comment by s4w3d0ff** [comment]
It seems that poloniex is returning captcha instead of json. In the past this has been because of the location/region of the IP address being used. The latest release of this repo has a new "proxies" argument for the `poloniex.Poloniex` object:

```python
from poloniex import Poloniex
Poloniex(proxies={'http': 'socks5://127.0.0.1:1080', 
                  'https': 'socks5://127.0.0.1:1080'}).returnTicker()
```
You could try using a vpn or contact poloniex support and see if they can remove the captcha from your IP.

**Comment by phyzixmusic** [comment]
my console says that proxies is an unexpected argument :(

**Comment by Pac23** [comment]
MIne too @phyzixmusic

**Comment by dstaeger** [comment]
Hi have the same problem like Pankul94 discribed. But just since 18th March 2018 5:55 am.

**This works fine:**
```
import urllib2
import json
ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/public?command=returnTicker'))
```

**The one below fails and gives me the following response as a html in the poloniex webpage design:** 

> Connection Error. Please try again in a few minutes


```
from poloniex import Poloniex
Poloniex().returnTicker()
```

So I wonder why. I will have a look at the difference in communication and try to understand why this only fails now and did not before. Happy about any input if someone knows more.

**Comment by Pac23** [comment]
@dstaeger maybe they say that you were requesting too much and got a captcha for your ip,same thing happened to my tracker.Certain countries ip's have a captcha now.

**Comment by dstaeger** [comment]
thanks for your input @Pac23 
But if an IP related captcha is the case, then both requests (direct request or using the python module) should get that captcha, right? or do I understand something fundamentally wrong here?

**Comment by bartgrefte** [comment]
Even though I do not use this Python wrapper, I thought it might help mentioning that I also have problems starting at the same time as dstaeger, I'm using Profit Trailer instead.

The strange thing is, so far I've only seen 3 people (including myself) reporting problems there. I would've expected more if everyone is running into this.

**Comment by dstaeger** [comment]
And just now the problem I described earlier:
> I have the same problem like @Pankul94 discribed. But just since 18th March 2018 5:55 am UTC.
> 
does not exist anymore on one of my computers (IP in Europe), but still exists on another (IP in US). Strange behavior, but certainly related to some specific change in response behavior of the servers of Poloniex, I cannot imagine anything else. The response behavior seems to depend on both ip and request details. What I can say is that nothing fundamentally changed in my requests recently so I assume its a technical problem on the side of Poloniex, thats the only thing I can think of at the moment.

**Comment by bartgrefte** [comment]
Well, still no change here (EU IP), although some servers could think I'm in the US due to my IPv6-tunnelprovider being located there, but I checked, the bots are using IPv4 and that address is registered in NL.

Someone from ProfitTrailer read my Tweets and has opened a support ticket. They are gonna look into this. If they find anything, I'll post it here.

**Comment by dstaeger** [comment]
All of my IP's are good now. I will post back here anyways if I got to understand more about such events.

**Comment by bartgrefte** [comment]
They are running normally again here as well, since around 14:30/14:40 (GMT+1/Amsterdam) according to the logs.

Same here, if PT-support figures it out, I'll post the info here.

**Comment by BruceDai003** [comment]
My IP is in China if without VPN, I was initially use `urllib2` to get the response from poloniex.com, but encountered the `captcha` problem. Then I switched to this `poloniex` module, and unexpectedly no captcha problem the first time or day I run it. But several days later( yesterday), I tried to download some data with `poloniex`, then sadly a HTTP 403 Error came up, I think it's related to the Captcha. 
So, my question is:
1. Could you add a proxy configuration to this `poloniex` class? I saw there was this option once before, but somehow it doesn't exist anymore, may I ask why?

2. Could you provide some way to check if there is a Captcha returned, just pop up the Captcha picture, and let the end user( me) input the correct numbers/digits on the Captcha and send it back to the website, and get the data downloaded?

Much appreciated.
